# Demo Array Class: MiniNumPy vs NumPy Comparison

In [1]:
import MiniNumPy as mnp
import numpy as np
import time

## Core Array Class

### Initialize

In [2]:
# Empty Matrix
A0 =[]

# 1D Vector
A1 = [1, 2, 3, 4, 5]

# 2D Matrix
A2 = [
    [1, 2, 3],
    [4, 5, 6]
]

# 3D Matrix 
A3 = [
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]

# 4D Matrix 
A4 = [
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
]

# 5D Matrix 
A5 = [
    [
        [
            [[1, 2], [3, 4]],
            [[5, 6], [7, 8]]
        ],
        [
            [[9, 10], [11, 12]],
            [[13, 14], [15, 16]]
        ]
    ],
    [
        [
            [[17, 18], [19, 20]],
            [[21, 22], [23, 24]]
        ],
        [
            [[25, 26], [27, 28]],
            [[29, 30], [31, 32]]
        ]
    ]
]

### Test case Mininumpy vs Numpy 

In [3]:
# Datasets
datasets = [
    ("Empty testcase", A0),
    ("1D testcase", A1),
    ("2D testcase", A2),
    ("3D testcase", A3),
    ("4D testcase", A4),
    ("5D testcase", A5),
]

#### Print

In [4]:
def print_two_column_arrays(title, mn_arr, np_arr):
    print("=" * 60)
    print(title)
    print("MiniNumPy Array".ljust(30) + " | " + "NumPy Array")
    print("-" * 60)

    # Convert each array to a list of formatted lines
    mn_lines = str(mn_arr).split("\n")
    np_lines = str(np_arr).split("\n")

    max_lines = max(len(mn_lines), len(np_lines))

    # Pad the shorter one to match
    if len(mn_lines) < max_lines:
        mn_lines += [""] * (max_lines - len(mn_lines))
    if len(np_lines) < max_lines:
        np_lines += [""] * (max_lines - len(np_lines))

    # Print line by line in two columns
    for left, right in zip(mn_lines, np_lines):
        print(left.ljust(30) + " | " + right)

    print()


In [5]:
for title, data in datasets:
    mn = mnp.array(data)
    npn = np.array(data)

    print_two_column_arrays(title, mn, npn)


Empty testcase
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[]                             | []

1D testcase
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[1 2 3 4 5]                    | [1 2 3 4 5]

2D testcase
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 2 3]                       | [[1 2 3]
 [4 5 6]]                      |  [4 5 6]]

3D testcase
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[1 2]                        | [[[1 2]
  [3 4]]                       |   [3 4]]
                               | 
 [[5 6]                        |  [[5 6]
  [7 8]]]                      |   [7 8]]]

4D testcase
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[[1 2]                       | [[[

#### Shape, ndim. size

In [33]:
for title, data in datasets:
    print("="*60)
    print(title)

    mn = mnp.array(data)
    npn = np.array(data)

    print(f"{'':<12}{'MiniNumPy':<20}{'NumPy'}")
    print("-" * 60)

    print(f"{'shape':<12}| {str(mn.shape):<18}| {npn.shape}")
    print(f"{'ndim':<12}| {str(mn.ndim):<18}| {npn.ndim}")
    print(f"{'size':<12}| {str(mn.size):<18}| {npn.size}")

    print()

Empty testcase
            MiniNumPy           NumPy
------------------------------------------------------------
shape       | (0,)              | (0,)
ndim        | 1                 | 1
size        | 0                 | 0

1D testcase
            MiniNumPy           NumPy
------------------------------------------------------------
shape       | (5,)              | (5,)
ndim        | 1                 | 1
size        | 5                 | 5

2D testcase
            MiniNumPy           NumPy
------------------------------------------------------------
shape       | (2, 3)            | (2, 3)
ndim        | 2                 | 2
size        | 6                 | 6

3D testcase
            MiniNumPy           NumPy
------------------------------------------------------------
shape       | (2, 2, 2)         | (2, 2, 2)
ndim        | 3                 | 3
size        | 8                 | 8

4D testcase
            MiniNumPy           NumPy
------------------------------------------------

#### Transpose

In [7]:
# Clasical transpose
for title, data in datasets:
    mn = mnp.array(data)
    npn = np.array(data)

    if mn.ndim < 2:
        print("="*60)
        print(title)
        print("Transpose skipped (ndim < 2)\n")
        continue

    print_two_column_arrays(
        title + " — transpose",
        mn.transpose(),
        np.transpose(npn)
    )


Empty testcase
Transpose skipped (ndim < 2)

1D testcase
Transpose skipped (ndim < 2)

2D testcase — transpose
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 4]                         | [[1 4]
 [2 5]                         |  [2 5]
 [3 6]]                        |  [3 6]]

3D testcase — transpose
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[1 5]                        | [[[1 5]
  [3 7]]                       |   [3 7]]
                               | 
 [[2 6]                        |  [[2 6]
  [4 8]]]                      |   [4 8]]]

4D testcase — transpose
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[[1 9]                       | [[[[ 1  9]
   [5 13]]                     |    [ 5 13]]
                               | 
  [[3 11]                      |   [[ 3 11]
   [7 15]]]                    |

In [8]:
# 4D test transpose with mixed axes
title = "4D transpose test"
data = A4

mn = mnp.array(data)
npn = np.array(data)

axes_list = [
    (0, 1, 2, 3),   
    (0, 3, 1, 2),
    (3, 2, 1, 0),
    (1, 0, 3, 2),
    (2, 3, 0, 1),
]

for axes in axes_list:
    print_two_column_arrays(
        f"{title} — axes={axes}",
        mn.transpose(axes),
        np.transpose(npn, axes)
    )


4D transpose test — axes=(0, 1, 2, 3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[[1 2]                       | [[[[ 1  2]
   [3 4]]                      |    [ 3  4]]
                               | 
  [[5 6]                       |   [[ 5  6]
   [7 8]]]                     |    [ 7  8]]]
                               | 
                               | 
 [[[9 10]                      |  [[[ 9 10]
   [11 12]]                    |    [11 12]]
                               | 
  [[13 14]                     |   [[13 14]
   [15 16]]]]                  |    [15 16]]]]

4D transpose test — axes=(0, 3, 1, 2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[[1 3]                       | [[[[ 1  3]
   [5 7]]                      |    [ 5  7]]
                               | 
  [[2 4]                       |   [[ 2  4]
   [6 8]]]                     |    [ 6  8]]]
   

#### Reshape

In [35]:
# dataset
mn_x = mnp.arange(12)    
np_x = np.arange(12)

In [37]:
print_two_column_arrays(
    "reshape 1D → 2D (3,4)",
    mn_x.reshape((3,4)),
    np_x.reshape((3,4))
)

print_two_column_arrays(
    "reshape 1D → 2D (4,3)",
    mn_x.reshape((4,3)),
    np_x.reshape((4,3))
)

print_two_column_arrays(
    "reshape 1D → 3D (2,2,3)",
    mn_x.reshape((2,2,3)),
    np_x.reshape((2,2,3))
)


reshape 1D → 2D (3,4)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0 1 2 3]                     | [[ 0  1  2  3]
 [4 5 6 7]                     |  [ 4  5  6  7]
 [8 9 10 11]]                  |  [ 8  9 10 11]]

reshape 1D → 2D (4,3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0 1 2]                       | [[ 0  1  2]
 [3 4 5]                       |  [ 3  4  5]
 [6 7 8]                       |  [ 6  7  8]
 [9 10 11]]                    |  [ 9 10 11]]

reshape 1D → 3D (2,2,3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[0 1 2]                      | [[[ 0  1  2]
  [3 4 5]]                     |   [ 3  4  5]]
                               | 
 [[6 7 8]                      |  [[ 6  7  8]
  [9 10 11]]]                  |   [ 9 10 11]]]



## Array Creation

#### Test Zero


In [9]:
sizes = [
    (3,),
    (2, 3),
    (2, 2, 2),
    (2, 3, 4, 5)
]

for shape in sizes:
    print_two_column_arrays(
        f"zeros{shape}",
        mnp.zeros(shape),
        np.zeros(shape, dtype=int)
    )



zeros(3,)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[0 0 0]                        | [0 0 0]

zeros(2, 3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0 0 0]                       | [[0 0 0]
 [0 0 0]]                      |  [0 0 0]]

zeros(2, 2, 2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[0 0]                        | [[[0 0]
  [0 0]]                       |   [0 0]]
                               | 
 [[0 0]                        |  [[0 0]
  [0 0]]]                      |   [0 0]]]

zeros(2, 3, 4, 5)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[[0 0 0 0 0]                 | [[[[0 0 0 0 0]
   [0 0 0 0 0]                 |    [0 0 0 0 0]
   [0 0 0 0 0]                 |    [0 0 0 0 0]
   [0 0 0 0 0]]                |    [0 0 0 0 0]

#### Test ones

In [10]:
for shape in sizes:
    print_two_column_arrays(
        f"ones{shape}",
        mnp.ones(shape),
        np.ones(shape, dtype=int)
    )


ones(3,)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[1 1 1]                        | [1 1 1]

ones(2, 3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 1 1]                       | [[1 1 1]
 [1 1 1]]                      |  [1 1 1]]

ones(2, 2, 2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[1 1]                        | [[[1 1]
  [1 1]]                       |   [1 1]]
                               | 
 [[1 1]                        |  [[1 1]
  [1 1]]]                      |   [1 1]]]

ones(2, 3, 4, 5)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[[1 1 1 1 1]                 | [[[[1 1 1 1 1]
   [1 1 1 1 1]                 |    [1 1 1 1 1]
   [1 1 1 1 1]                 |    [1 1 1 1 1]
   [1 1 1 1 1]]                |    [1 1 1 1 1]]
  

#### Test eyes

In [11]:
for n in [2, 3, 4]:
    print_two_column_arrays(
        f"eye({n})",
        mnp.eye(n,n,1),
        np.eye(n,n,1, dtype=int)
    )


eye(2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0 1]                         | [[0 1]
 [0 0]]                        |  [0 0]]

eye(3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0 1 0]                       | [[0 1 0]
 [0 0 1]                       |  [0 0 1]
 [0 0 0]]                      |  [0 0 0]]

eye(4)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0 1 0 0]                     | [[0 1 0 0]
 [0 0 1 0]                     |  [0 0 1 0]
 [0 0 0 1]                     |  [0 0 0 1]
 [0 0 0 0]]                    |  [0 0 0 0]]



#### Test Identity 

In [12]:
for n in [2, 3, 4]:
    print_two_column_arrays(
        f"identity({n})",
        mnp.identity(n),
        np.identity(n, dtype=int)
    )


identity(2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 0]                         | [[1 0]
 [0 1]]                        |  [0 1]]

identity(3)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 0 0]                       | [[1 0 0]
 [0 1 0]                       |  [0 1 0]
 [0 0 1]]                      |  [0 0 1]]

identity(4)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 0 0 0]                     | [[1 0 0 0]
 [0 1 0 0]                     |  [0 1 0 0]
 [0 0 1 0]                     |  [0 0 1 0]
 [0 0 0 1]]                    |  [0 0 0 1]]



#### Test arrage

In [13]:
# Test arange
arange_tests = [
    (0, 5, 1),
    (2, 10, 2),
    (5, -5, -2),
    (0, 1, 0.1),
]

for start, stop, step in arange_tests:
    title = f"arange({start}, {stop}, {step})"
    print_two_column_arrays(
        title,
        mnp.arange(start, stop, step),
        np.arange(start, stop, step)
    )


arange(0, 5, 1)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[0 1 2 3 4]                    | [0 1 2 3 4]

arange(2, 10, 2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[2 4 6 8]                      | [2 4 6 8]

arange(5, -5, -2)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[5 3 1 -1 -3]                  | [ 5  3  1 -1 -3]

arange(0, 1, 0.1)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[0 0.1 0.2 0.30000000000000004 0.4 0.5 0.6 0.7 0.7999999999999999 0.8999999999999999 0.9999999999999999] | [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]



#### Test linspace

In [14]:
# Test linspace
linspace_tests = [
    (0, 1, 5),
    (1, 10, 10),
    (-5, 5, 6),
    (0, 2*np.pi, 8),
]

for start, stop, num in linspace_tests:
    title = f"linspace({start}, {stop}, {num})"
    print_two_column_arrays(
        title,
        mnp.linspace(start, stop, num),
        np.linspace(start, stop, num)
    )


linspace(0, 1, 5)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[0.0 0.25 0.5 0.75 1.0]        | [0.   0.25 0.5  0.75 1.  ]

linspace(1, 10, 10)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0] | [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

linspace(-5, 5, 6)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[-5.0 -3.0 -1.0 1.0 3.0 5.0]   | [-5. -3. -1.  1.  3.  5.]

linspace(0, 6.283185307179586, 8)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[0.0 0.8975979010256552 1.7951958020513104 2.6927937030769655 3.5903916041026207 4.487989505128276 5.385587406153931 6.283185307179586] | [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
                               |  5.38558741 6.28318531]



## Element-wise Operator

In [15]:
elem_A = [[1, 2], [3, 4]]
elem_B = [[5, 6], [7, 8]]
scalar = 10

mnA = mnp.array(elem_A)
mnB = mnp.array(elem_B)
npA = np.array(elem_A)
npB = np.array(elem_B)

In [16]:
print_two_column_arrays(
    "A * scalar (elementwise)",
    mnA * scalar,
    npA * scalar
)

print_two_column_arrays(
    "A / scalar",
    mnA / scalar,
    npA / scalar
)

print_two_column_arrays(
    "A ** scalar",
    mnA ** 2,
    npA ** 2
)

print_two_column_arrays("A + B", mnA + mnB, npA + npB)
print_two_column_arrays("A - B", mnA - mnB, npA - npB)


A * scalar (elementwise)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[10 20]                       | [[10 20]
 [30 40]]                      |  [30 40]]

A / scalar
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0.1 0.2]                     | [[0.1 0.2]
 [0.3 0.4]]                    |  [0.3 0.4]]

A ** scalar
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1 4]                         | [[ 1  4]
 [9 16]]                       |  [ 9 16]]

A + B
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[6 8]                         | [[ 6  8]
 [10 12]]                      |  [10 12]]

A - B
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[-4 -4]                       | [[-4 -4]
 [-4 -4]]           

#### Matmul

In [17]:
M1 = [[1, 2, 3],
      [4, 5, 6]]

M2 = [[7, 8],
      [9, 10],
      [11, 12]]

v = [1, 2, 3]

mnM1 = mnp.array(M1)
mnM2 = mnp.array(M2)
mnv  = mnp.array(v)

npM1 = np.array(M1)
npM2 = np.array(M2)
npv  = np.array(v)


In [18]:
print_two_column_arrays(
    "2D @ 2D",
    mnM1 @ mnM2,
    npM1 @ npM2
)

print_two_column_arrays(
    "2D @ 1D",
    mnM1 @ mnv,
    npM1 @ npv
)

print_two_column_arrays(
    "1D @ 2D",
    mnv @ mnM2,
    npv @ npM2
)



2D @ 2D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[58 64]                       | [[ 58  64]
 [139 154]]                    |  [139 154]]

2D @ 1D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[14 32]                        | [14 32]

1D @ 2D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[58 64]                        | [58 64]



#### exp, log, sqrt, abs

In [19]:
E = [
    [1, 2, 3],
    [4, 5, 6]
]

E_neg = [
    [-1, -2, -3],
    [ 4,  9, 16]
]

mnE  = mnp.array(E)
mnE2 = mnp.array(E_neg)

npE  = np.array(E)
npE2 = np.array(E_neg)


In [20]:
print_two_column_arrays(
    "exp(E)",
    mnE.exp(),
    np.exp(npE)
)

print_two_column_arrays(
    "sqrt(E)",
    mnE.sqrt(),
    np.sqrt(mnE)
)

print_two_column_arrays(
    "log(E)",
    mnE.log(),
    np.log(npE)
)

print_two_column_arrays(
    "abs(E_neg)",
    mnE2.abs(),
    np.abs(npE2)
)


exp(E)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[2.718281828459045 7.38905609893065 20.085536923187668] | [[  2.71828183   7.3890561   20.08553692]
 [54.598150033144236 148.4131591025766 403.4287934927351]] |  [ 54.59815003 148.4131591  403.42879349]]

sqrt(E)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[1.0 1.4142135623730951 1.7320508075688772] | [[1.0 1.4142135623730951 1.7320508075688772]
 [2.0 2.23606797749979 2.449489742783178]] |  [2.0 2.23606797749979 2.449489742783178]]

log(E)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0.0 0.6931471805599453 1.0986122886681098] | [[0.         0.69314718 1.09861229]
 [1.3862943611198906 1.6094379124341003 1.791759469228055]] |  [1.38629436 1.60943791 1.79175947]]

abs(E_neg)
MiniNumPy Array                | NumPy Array
----------------------------------

##### Additional features

In [32]:
E1 = mnp.array([[100, -267, 39],
                [400, 5,   16],
                [250, -75,  0]])

print("Sqrt of first column of E1:", E1.sqrt(0))
print("Log of second row of E1:", E1.log(None, 1))
print("Exp of second column of E1:", E1.exp(1))
print("Absolute value of 3rd row of E1:", E1.abs(None, 2))

Sqrt of first column of E1: [[10.0]
 [20.0]
 [15.811388300841896]]
Log of second row of E1: [5.991464547107982 1.6094379124341003 2.772588722239781]
Exp of second column of E1: [[1.105028125193164e-116]
 [148.4131591025766]
 [2.6786369618080778e-33]]
Absolute value of 3rd row of E1: [250 75 0]


#### sum, min, max, argmin, argmax

In [21]:
R1 = [1, 5, -3, 4]

R2 = [
    [1, 6, 3],
    [9, 5, 2]
]

R3 = [
    [[1,  2], [3, -1]],
    [[0, -5], [7,  8]]
]

reduction_tests = [
    ("1D reduction", R1),
    ("2D reduction", R2),
    ("3D reduction", R3),
]


In [22]:
def print_two_column_scalar(title, mn_val, np_val):
    print("=" * 60)
    print(title)
    print(f"{'MiniNumPy':<20} | NumPy")
    print("-" * 60)
    print(f"{str(mn_val):<20} | {np_val}")
    print()


In [23]:
for title, data in reduction_tests:
    mn = mnp.array(data)
    npn = np.array(data)

    # SUM
    print_two_column_scalar(
        title + " — sum",
        mn.sum(),
        np.sum(npn)
    )

    # MEAN
    print_two_column_scalar(
        title + " — mean",
        mn.mean(),
        np.mean(npn)
    )

    # MIN
    print_two_column_scalar(
        title + " — min",
        mn.min(),
        np.min(npn)
    )

    # MAX
    print_two_column_scalar(
        title + " — max",
        mn.max(),
        np.max(npn)
    )

    # ARGMIN
    print_two_column_scalar(
        title + " — argmin",
        mn.arg_min(),
        np.argmin(npn)
    )

    # ARGMAX
    print_two_column_scalar(
        title + " — argmax",
        mn.arg_max(),
        np.argmax(npn)
    )


1D reduction — sum
MiniNumPy            | NumPy
------------------------------------------------------------
7.0                  | 7

1D reduction — mean
MiniNumPy            | NumPy
------------------------------------------------------------
1.75                 | 1.75

1D reduction — min
MiniNumPy            | NumPy
------------------------------------------------------------
-3.0                 | -3

1D reduction — max
MiniNumPy            | NumPy
------------------------------------------------------------
5.0                  | 5

1D reduction — argmin
MiniNumPy            | NumPy
------------------------------------------------------------
(2,)                 | 2

1D reduction — argmax
MiniNumPy            | NumPy
------------------------------------------------------------
(1,)                 | 1

2D reduction — sum
MiniNumPy            | NumPy
------------------------------------------------------------
26.0                 | 26

2D reduction — mean
MiniNumPy            | 

##### Additional features

In [25]:
R4 = mnp.array([
    [3, 1, 4],
    [1, 5, 9],
    [2, 6, 5]
])

print("Sum of 2nd column:", R4.sum(1))
print("Mean of 2nd column:", R4.mean(1))
print("Min of 1st row:", R4.min(None,0))
print("Max of 3rd row:", R4.max(None,2))
print("Arg_min of 1st row:", R4.arg_min(None,0))
print("Arg_max of 3rd row:", R4.arg_max(None,2))

Sum of 2nd column: 12.0
Mean of 2nd column: 4.0
Min of 1st row: 1.0
Max of 3rd row: 6.0
Arg_min of 1st row: (1,)
Arg_max of 3rd row: (1,)
