# Demo Linear Algebra: MiniNumPy vs NumPy Comparison

In [36]:
import MiniNumPy as mnp
import numpy as np
import time
import random

## Matrix/Vector Operations

### Dot product

In [7]:
def print_two_column_arrays(title, mn_arr, np_arr):
    print("=" * 60)
    print(title)
    print("MiniNumPy Array".ljust(30) + " | " + "NumPy Array")
    print("-" * 60)

    mn_lines = str(mn_arr).split("\n")
    np_lines = str(np_arr).split("\n")

    max_lines = max(len(mn_lines), len(np_lines))

    if len(mn_lines) < max_lines:
        mn_lines += [""] * (max_lines - len(mn_lines))
    if len(np_lines) < max_lines:
        np_lines += [""] * (max_lines - len(np_lines))

    for left, right in zip(mn_lines, np_lines):
        print(left.ljust(30) + " | " + right)

    print()

def print_two_column_scalar(title, mn_val, np_val):
    print("=" * 60)
    print(title)
    print(f"{'MiniNumPy':<20} | NumPy")
    print("-" * 60)
    print(f"{str(mn_val):<20} | {np_val}")
    print()


In [8]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]

M1 = [
    [1, 2, 3],
    [4, 5, 6]
]

M2 = [
    [7,  8],
    [9, 10],
    [11,12]
]

mnv1 = mnp.array(v1)
mnv2 = mnp.array(v2)

mnM1 = mnp.array(M1)
mnM2 = mnp.array(M2)

npv1 = np.array(v1)
npv2 = np.array(v2)

npM1 = np.array(M1)
npM2 = np.array(M2)


In [9]:
print_two_column_scalar(
    "CASE 1: 1D dot 1D",
    mnp.dot(mnv1, mnv2),
    np.dot(npv1, npv2)
)

print_two_column_arrays(
    "CASE 2: 1D dot 2D",
    mnp.dot(mnv1, mnM2),
    np.dot(npv1, npM2)
)

print_two_column_arrays(
    "CASE 3: 2D dot 1D",
    mnp.dot(mnM1, mnv1),
    np.dot(npM1, npv1)
)

print_two_column_arrays(
    "CASE 4: 2D dot 2D",
    mnp.dot(mnM1, mnM2),
    np.dot(npM1, npM2)
)


CASE 1: 1D dot 1D
MiniNumPy            | NumPy
------------------------------------------------------------
32                   | 32

CASE 2: 1D dot 2D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[58 64]                        | [58 64]

CASE 3: 2D dot 1D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[14 32]                        | [14 32]

CASE 4: 2D dot 2D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[58 64]                       | [[ 58  64]
 [139 154]]                    |  [139 154]]



### General matrix multiplication

In [10]:
# 2D matrices
mn_A = mnp.arange(6).reshape((2,3))    # [[0,1,2],[3,4,5]]
mn_B = mnp.arange(6,12).reshape((3,2))

np_A = np.arange(6).reshape((2,3))
np_B = np.arange(6,12).reshape((3,2))

# 3D
mn_A3 = mnp.arange(24).reshape((2,3,4))
mn_B3 = mnp.arange(48).reshape((4,12))

np_A3 = np.arange(24).reshape((2,3,4))
np_B3 = np.arange(48).reshape((4,12))

# BROADCAST batch matmul
mn_A_b = mnp.arange(12).reshape((3,4))
mn_B_b = mnp.arange(40).reshape((5,4,2))

np_A_b = np.arange(12).reshape((3,4))
np_B_b = np.arange(40).reshape((5,4,2))


In [11]:
print_two_column_arrays(
    "matmul CASE4: 2D @ 2D",
    mnp.matmul(mn_A, mn_B),
    np.linalg.matmul(np_A, np_B)
)

print_two_column_arrays(
    "matmul CASE5: 3D @ 3D",
    mnp.matmul(mn_A3, mn_B3),
    np.linalg.matmul(np_A3, np_B3)
)

print_two_column_arrays(
    "matmul CASE6: broadcast batch",
    mnp.matmul(mn_A_b, mn_B_b),
    np.linalg.matmul(np_A_b, np_B_b)
)


matmul CASE4: 2D @ 2D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[28 31]                       | [[ 28  31]
 [100 112]]                    |  [100 112]]

matmul CASE5: 3D @ 3D
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[[168 174 180 186 192 198 204 210 216 222 228 234] | [[[ 168  174  180  186  192  198  204  210  216  222  228  234]
  [456 478 500 522 544 566 588 610 632 654 676 698] |   [ 456  478  500  522  544  566  588  610  632  654  676  698]
  [744 782 820 858 896 934 972 1010 1048 1086 1124 1162]] |   [ 744  782  820  858  896  934  972 1010 1048 1086 1124 1162]]
                               | 
 [[1032 1086 1140 1194 1248 1302 1356 1410 1464 1518 1572 1626] |  [[1032 1086 1140 1194 1248 1302 1356 1410 1464 1518 1572 1626]
  [1320 1390 1460 1530 1600 1670 1740 1810 1880 1950 2020 2090] |   [1320 1390 1460 1530 1600 1670 1740 1810 1880 1950 2020 2090]

### Norm

In [12]:
# N-D datasets (ndim != 2)
ND_tests = [
    ("1D v1",  mnp.arange(5),              np.arange(5)),
    ("1D v2",  mnp.arange(-3, 2),          np.arange(-3, 2)),
    ("3D C3",  mnp.arange(24).reshape((2,3,4)),  np.arange(24).reshape((2,3,4))),
    ("4D D4",  mnp.arange(48).reshape((2,2,3,4)),np.arange(48).reshape((2,2,3,4))),
]


In [13]:
for title, mn_x, np_x in ND_tests:
    print_two_column_scalar(
        f"{title} — norm(None/2)",
        mnp.norm(mn_x),
        np.linalg.norm(np_x)
    )

    print (mnp.norm(mn_x, 1))
    print (mnp.norm(mn_x, 3))
    


1D v1 — norm(None/2)
MiniNumPy            | NumPy
------------------------------------------------------------
5.477225575051661    | 5.477225575051661

10.0
4.0
1D v2 — norm(None/2)
MiniNumPy            | NumPy
------------------------------------------------------------
3.872983346207417    | 3.872983346207417

7.0
3.0
3D C3 — norm(None/2)
MiniNumPy            | NumPy
------------------------------------------------------------
65.75712889109438    | 65.75712889109438

276.0
23.0
4D D4 — norm(None/2)
MiniNumPy            | NumPy
------------------------------------------------------------
188.9973544788392    | 188.9973544788392

1128.0
47.0


In [14]:
# 2D datasets (ndim == 2)
D2_tests = [
    ("2D A",  mnp.arange(6).reshape((2,3)),     np.arange(6).reshape((2,3))),
    ("2D B",  mnp.arange(20).reshape((4,5)), np.arange(20).reshape((4,5))),
]

In [15]:
for title, mn_M, np_M in D2_tests:
    print_two_column_scalar(
        f"{title} — norm(None/Fro)",
        mnp.norm(mn_M),
        np.linalg.norm(np_M)
    )

    print_two_column_scalar(
        f"{title} — norm(1) (max column sum)",
        mnp.norm(mn_M, 1),
        np.linalg.norm(np_M, 1)
    )
    
    print_two_column_scalar(
        f"{title} — norm(2) (spectral)",
        mnp.norm(mn_M, 2),
        np.linalg.norm(np_M, 2)
    )

    print_two_column_scalar(
        f"{title} — norm(3) (max row sum)",
        mnp.norm(mn_M, 3),
        np.linalg.norm(np_M, np.inf)
    )


2D A — norm(None/Fro)
MiniNumPy            | NumPy
------------------------------------------------------------
7.416198487095663    | 7.416198487095663

2D A — norm(1) (max column sum)
MiniNumPy            | NumPy
------------------------------------------------------------
7.0                  | 7.0

2D A — norm(2) (spectral)
MiniNumPy            | NumPy
------------------------------------------------------------
7.3484692283495345   | 7.3484692283495345

2D A — norm(3) (max row sum)
MiniNumPy            | NumPy
------------------------------------------------------------
12.0                 | 12.0

2D B — norm(None/Fro)
MiniNumPy            | NumPy
------------------------------------------------------------
49.69909455915671    | 49.69909455915671

2D B — norm(1) (max column sum)
MiniNumPy            | NumPy
------------------------------------------------------------
46.0                 | 46.0

2D B — norm(2) (spectral)
MiniNumPy            | NumPy
-----------------------------

### Determinant

In [16]:
det_tests = [
    ("1x1", mnp.arange(1).reshape((1,1)), np.arange(1).reshape((1,1))),
    
    ("2x2 simple", mnp.arange(4).reshape((2,2)), np.arange(4).reshape((2,2))),
    
    ("2x2 mixed", mnp.array([[3, -1], [2, 5]]), np.array([[3, -1], [2, 5]])),
    
    ("3x3", mnp.arange(9).reshape((3,3)), np.arange(9).reshape((3,3))),
    
    ("3x3 mixed", 
        mnp.array([[2, 4, 1], [3, -1, 5], [7, 0, 2]]),
        np.array([[2, 4, 1], [3, -1, 5], [7, 0, 2]])
    ),

    ("4x4", mnp.arange(16).reshape((4,4)), np.arange(16).reshape((4,4))),
]


In [17]:
for title, mn_M, np_M in det_tests:
    print_two_column_scalar(
        f"{title} — det",
        mnp.det(mn_M),
        np.linalg.det(np_M)
    )


1x1 — det
MiniNumPy            | NumPy
------------------------------------------------------------
0.0                  | 0.0

2x2 simple — det
MiniNumPy            | NumPy
------------------------------------------------------------
-2.0                 | -2.0

2x2 mixed — det
MiniNumPy            | NumPy
------------------------------------------------------------
17.0                 | 17.0

3x3 — det
MiniNumPy            | NumPy
------------------------------------------------------------
0.0                  | 0.0

3x3 mixed — det
MiniNumPy            | NumPy
------------------------------------------------------------
119.0                | 118.99999999999993

4x4 — det
MiniNumPy            | NumPy
------------------------------------------------------------
0.0                  | 0.0



### Inverse

In [20]:
inv_tests = [
    ("2x2 simple", 
        mnp.array([[1, 2], [3, 4]]),
        np.array([[1, 2], [3, 4]])),

    ("2x2 mixed",
        mnp.array([[4, 7], [2, 6]]),
        np.array([[4, 7], [2, 6]])),

    ("3x3 basic",
        mnp.arange(9).reshape((3,3)) + mnp.ones((3,3)),   # ensure invertible
        (np.arange(9).reshape((3,3)) + 1)
    ),

    ("3x3 random",
        mnp.array([[2, 4, 1], [3, 5, 7], [1, 0, 6]]),
        np.array([[2, 4, 1], [3, 5, 7], [1, 0, 6]])
    ),

    # Singular (det = 0) — expect error
    ("singular", 
        mnp.array([[1, 2], [2, 4]]),
        np.array([[1, 2], [2, 4]])
    ),
]


In [22]:
for title, mn_M, np_M in inv_tests:
    print("="*60)
    print(title)

    try:
        mn_inv = mnp.inv(mn_M)
    except Exception as e:
        mn_inv = f"Error: {type(e).__name__}"

    try:
        np_inv = np.linalg.inv(np_M)
    except Exception as e:
        np_inv = f"Error: {type(e).__name__}"

    if isinstance(mn_inv, str):
        print("MiniNumPy:", mn_inv)
        print("NumPy    :", np_inv)
        print()
    else:
        print_two_column_arrays(title + " — inverse", mn_inv, np_inv)


2x2 simple
2x2 simple — inverse
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[-2.0 1.0]                    | [[-2.   1. ]
 [1.5 -0.5]]                   |  [ 1.5 -0.5]]

2x2 mixed
2x2 mixed — inverse
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0.6000000000000001 -0.7000000000000001] | [[ 0.6 -0.7]
 [-0.2 0.4]]                   |  [-0.2  0.4]]

3x3 basic
MiniNumPy: Error: ValueError
NumPy    : Error: LinAlgError

3x3 random
3x3 random — inverse
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[2.7272727272727275 -2.1818181818181817 2.090909090909091] | [[ 2.72727273 -2.18181818  2.09090909]
 [-1.0 1.0 -1.0]               |  [-1.          1.         -1.        ]
 [-0.45454545454545453 0.36363636363636365 -0.18181818181818182]] |  [-0.45454545  0.36363636 -0.18181818]]

singular
MiniNumPy: Error: ValueError

### eig

In [32]:
A_real = [
    [ 4,  2,  0,  1],
    [ 2,  3,  2,  0],
    [ 0,  2,  2,  2],
    [ 1,  0,  2,  3]
]

mnA_real = mnp.array(A_real)
npA_real = np.array(A_real)

eigvals, eigvecs = mnp.eig(mnA_real)
np_eigvals, np_eigvecs = np.linalg.eig(npA_real)

print(eigvals)
print(np_eigvals)

print_two_column_arrays(
    "Eigenvectors",
    eigvecs,
    np_eigvecs
)

[6.5849593014465055 3.6649593546750894 2.559527473872663 -0.8094461299942541]
[-0.80944613  6.5849593   2.55952747  3.66495935]
Eigenvectors
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0.5899077246220423 -0.5633428088196242 0.4922341382520887 0.30390674444915633] | [[-0.30390674  0.58990772 -0.49223452 -0.56334248]
 [0.5631460683208283 -0.21947982558581486 -0.6088551402183353 -0.5138000877046687] |  [ 0.51380009  0.56314607  0.60885499 -0.21948023]
 [0.41952014322435716 0.4903700018153708 -0.3581422386827186 0.6747401333994728] |  [-0.67474013  0.41952014  0.35814257  0.49036976]
 [0.3985953230973139 0.627702753882464 0.5086601107225395 -0.43402294056080953]] |  [ 0.43402294  0.39859532 -0.50865969  0.62770309]]



For matrices which have real eigenvalue, my implemented algorithm and np's algorithm work identically, provides same result

In [35]:
A_complex = [
    [0, -1,  2,  3],
    [1,  0,  4, -2],
    [0,  0,  1,  5],
    [-1, 2, -3,  0]
]

mnA_complex = mnp.array(A_complex)
npA_complex = np.array(A_complex)

eigvals_c, eigvecs_c = mnp.eig(mnA_complex)
np_eigvals_c, np_eigvecs_c = np.linalg.eig(npA_complex)

print(eigvals_c)
print(np_eigvals_c)

print_two_column_arrays(
    "Eigenvectors (complex)",
    eigvecs_c,
    np_eigvecs_c
)

[-0.04917466287301775 -0.612442217053055 2.068636627578488 -0.40701974765241766]
[-0.33080844+4.9831612j -0.33080844-4.9831612j -0.40701975+0.j
  2.06863663+0.j       ]
Eigenvectors (complex)
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[0.5926859350773062 -0.1646145996494199 -0.02848727690685726 0.7879174392017427] | [[ 0.00556508-0.42850247j  0.00556508+0.42850247j -0.96345536+0.j
 [0.16444065366128874 0.7793124920047673 0.6016027253053308 0.060872589348291865] |    0.16376354+0.j        ]
 [0.5310145605286393 -0.47215033953346486 0.5149883868277821 -0.4794627773013568] |  [-0.56963245+0.j         -0.56963245-0.j         -0.1342543 +0.j
 [-0.5828431952863145 -0.3776878741315564 0.6099586849878847 0.3815705466231282]] |    0.86869567+0.j        ]
                               |  [ 0.22976684-0.43070223j  0.22976684+0.43070223j  0.22313004+0.j
                               |    0.45716764+0.j        ]
                     

But for the matrices whose eigenvalue are complex, my algorithm is fail to compute the eigenvalue.

## Factorizations and Solver

### LU decomposition

In [43]:
def random_float_matrix(n, low=-10.0, high=10.0):
    data = [[random.uniform(low, high) for _ in range(n)] for _ in range(n)]
    return mnp.array(data)

T = random_float_matrix(4)
print("Random Matrix T:")
print(T)
P, L, U = T.LU_Decomposition()

print("Permutaion matrix:")
print(P)
print("Lower triagular matrix")
print(L)
print("Upper triagular matrix")
print(U)
print("="* 30 + "Validation Result" + "="*30)
print(L@U - P@T)

Random Matrix T:
[[-6.7303729834911685 -2.656772025418766 1.6310335625406225 7.269920080272399]
 [1.7871585778186656 7.486728772504652 -1.5710509449338428 -6.608392915289036]
 [3.300588955567413 -4.267107701733948 0.3701948267572792 -0.4013555135387499]
 [-8.48632764782253 2.7759502074898794 -8.207812573660975 6.759876464398861]]
Permutaion matrix:
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]]
Lower triagular matrix
[[1 0 0 0]
 [-0.2105926912069233 1 0 0]
 [0.7930842718779644 -0.6019253739357735 1 0]
 [-0.3889301818807688 -0.3949112985244394 -0.6702652569109057 1]]
Upper triagular matrix
[[-8.48632764782253 2.7759502074898794 -8.207812573660975 6.759876464398861]
 [0.0 8.071323597356363 -3.299556283743131 -5.184812338424938]
 [0.0 0.0 6.154433971319124 -1.2121017290736025]
 [0.0 0.0 0.0 -0.6322061807611713]]
==============================Validation Result==============================
[[0.0 0.0 0.0 0.0]
 [0.0 8.881784197001252e-16 0.0 0.0]
 [0.0 -4.440892098500626e-16 8.881784197001252e

### QR decomposition

In [44]:
T1 = random_float_matrix(4)
print("Random Matrix T1:")
print(T1)

Q, R = mnp.qr_decomposition(T)

print("Q matrix:")
print(Q)
print("R matrix:")
print(R)
print("="* 30 + "Validation Result" + "="*30)
print(Q@R - T)

Random Matrix T1:
[[-0.6540417235175138 -0.29077431887531446 -3.736633666765565 1.7487879351540698]
 [0.8865570519473369 8.866059334731446 -6.056392166265132 -9.913295418662555]
 [-2.7464056539970887 -7.329032933133113 -9.276956032434052 6.262186591615464]
 [3.738740683716893 9.354422056916878 -5.567345120422944 -9.9142184171923]]
Q matrix:
[[-0.5871318836322674 -0.3167683520947614 0.5828375257799876 -0.463933595330467]
 [0.1559048487681209 0.8040839665855951 0.15420560844171236 -0.5525968540769016]
 [0.2879307009182928 -0.4360258477692692 -0.4978816456805924 -0.6921641701505339]
 [-0.7403146228609262 0.25097459207703643 -0.6234058996850836 -0.017637957588134846]]
R matrix:
[[11.463136598636051 -0.5566149616817693 4.9803878581086956 -10.418680338303364]
 [0 9.418802088651669 -4.001283615023667 -5.7450247755789885]
 [0 0 5.640848271560151 -0.7961883435847764]
 [0 0 0 0.4375904664705942]]
==============================Validation Result==============================
[[8.881784197001252e-1

### Unique solution solver

In [45]:
# solve AX = B
Sa = [
    [ 2,  1, -1],
    [-3, -1,  2],
    [-2,  1,  2]
]

Sb = [
    [8],
    [-11],
    [-3]
]

mnA = mnp.array(Sa)
mnB = mnp.array(Sb) 
npA = np.array(Sa)
npB = np.array(Sb)

mn_x = mnp.solve(mnA, mnB)
np_x = np.linalg.solve(npA, npB)

print_two_column_arrays(
    "Solving AX = B",
    mn_x,
    np_x
)

Solving AX = B
MiniNumPy Array                | NumPy Array
------------------------------------------------------------
[[2.000000000000002]           | [[ 2.]
 [2.999999999999999]           |  [ 3.]
 [-0.9999999999999971]]        |  [-1.]]

